name: Build CR6606
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install build-essential -y

      - name: Clone source
        run: git clone https://github.com/coolsnowwolf/lede --depth 1

      - name: Build config
        run: |
          cd lede
          echo -e "CONFIG_TARGET_ramips=y\nCONFIG_TARGET_ramips_mt7621=y\nCONFIG_TARGET_ramips_mt7621_DEVICE_xiaomi_mi-router-cr6606=y" > .config
          make defconfig

      - name: Download
        run: cd lede && make download -j8

      - name: Compile
        run: cd lede && make -j4 V=s

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: lede/bin/targets/ramips/mt7621/*
